web:
  restart: always
  build: ./web/
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: env
  volumes:
    - D:\Quellecode\DOCKER\PING\web:/data/web
  command: /usr/bin/gunicorn mydjango.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - D:\Quellecode\DOCKER\PING\web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  volumes:
    - D:\Quellecode\DOCKER\PING\postgres\docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - D:\Quellecode\DOCKER\PING\backups\postgresql:/backup
  env_file:
    - env
  expose:
    - "5432"
    
    redis:
  restart: always
  image: redis:latest
  expose:
    - "6379"

data:
  restart: always
  image: alpine
  volumes:
    - D:\Quellecode\DOCKER\PING\postgresql
  command: "true"
